--20220309 화면구현 과제 SQL 쿼리 테스트 
CREATE TABLE MEMBERS(
	SEQ NUMBER,
	NAME VARCHAR2(30) NOT NULL,
	ID VARCHAR2(30) NOT NULL,
	PASSWORD VARCHAR2 (200) NOT NULL,
	PHONE VARCHAR2 (20) NOT NULL,
	ADDRESS VARCHAR2(400),
	BIRTH DATE
);
CREATE SEQUENCE MEMBERS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
ALTER TABLE MEMBERS ADD CONSTRAINT MEMBERS_PK PRIMARY KEY(SEQ);

--회원가입 쿼리
INSERT INTO MEMBERS (SEQ, NAME, ID, PASSWORD, PHONE)
	VALUES (MEMBERS_SEQ.NEXTVAL, '김화면', 'UIUX', 
					'UIUX1!','01012121212');
				
INSERT INTO MEMBERS (SEQ, NAME, ID, PASSWORD, PHONE, ADDRESS, BIRTH)
	VALUES (MEMBERS_SEQ.NEXTVAL, '관리자', 'admin', 
					'admin','01012121212','12345서울시구로구구로동','1996-12-24');
--서울시 동물병원 API	
CREATE TABLE SEOULANIMALHOSPITAL(
SITEPOSTNO NUMBER,
RGTMBDSNO NUMBER,
TOTEPNUM NUMBER,
UPTAENM NUMBER,
LASTMODTS NUMBER,
CLGENDDT NUMBER,
UPDATEGBN CHAR(1),
RDNWHLADDR VARCHAR2(100),
DCBYMD NUMBER,
SITEWHLADDR VARCHAR2(100),
Y NUMBER,
DTLSTATEGBN NUMBER,
TRDSTATEGBN NUMBER,
X NUMBER,
OPNSFTEAMCODE NUMBER,
APVPERMYMD NUMBER,
LINDSEQNO NUMBER,
UPDATEDT DATE,
LINDPRCBGBNNM VARCHAR2(30),
BPLCNM VARCHAR2(100),
CLGSTDT NUMBER,
RDNPOSTNO NUMBER,
ROPNYMD NUMBER,
MGTNO NUMBER,
LINDJOBGBNNM VARCHAR2(100),
TRDSTATENM VARCHAR2(100),
SITEAREA NUMBER,
SITETEL NUMBER,
APVCANCELYMD NUMBER,
DTLSTATENM VARCHAR2(30)
);
COMMENT ON TABLE SEOULANIMALHOSPITAL IS '서울시_동물병원';

COMMENT ON COLUMN SEOULANIMALHOSPITAL.SITEPOSTNO IS '소재지우편번호';
COMMENT ON COLUMN SEOULANIMALHOSPITAL.RGTMBDSNO  IS '권리주체일련번호';
COMMENT ON COLUMN SEOULANIMALHOSPITAL.TOTEPNUM IS '총인원';
COMMENT ON COLUMN SEOULANIMALHOSPITAL.UPTAENM IS '업태구분명';
COMMENT ON COLUMN SEOULANIMALHOSPITAL.LASTMODTS IS '최종수정일자';
COMMENT ON COLUMN SEOULANIMALHOSPITAL.CLGENDDT IS '휴업종료일자';
COMMENT ON COLUMN SEOULANIMALHOSPITAL.UPDATEGBN IS '데이터갱신구분';
COMMENT ON COLUMN SEOULANIMALHOSPITAL.RDNWHLADDR IS '도로명주소';
COMMENT ON COLUMN SEOULANIMALHOSPITAL.DCBYMD IS '폐업일자';
COMMENT ON COLUMN SEOULANIMALHOSPITAL.SITEWHLADDR IS '지번주소';
COMMENT ON COLUMN SEOULANIMALHOSPITAL.Y IS '좌표정보(Y)';
COMMENT ON COLUMN SEOULANIMALHOSPITAL.DTLSTATEGBN IS '상세영업상태코드';
COMMENT ON COLUMN SEOULANIMALHOSPITAL.TRDSTATEGBN IS '영업상태코드';
COMMENT ON COLUMN SEOULANIMALHOSPITAL.X IS '좌표정보(X)';
COMMENT ON COLUMN SEOULANIMALHOSPITAL.OPNSFTEAMCODE IS '개방자치단체코드';
COMMENT ON COLUMN SEOULANIMALHOSPITAL.APVPERMYMD IS '인허가일자';
COMMENT ON COLUMN SEOULANIMALHOSPITAL.LINDSEQNO IS '축산일련번호';
COMMENT ON COLUMN SEOULANIMALHOSPITAL.UPDATEDT IS '데이터갱신일자';
COMMENT ON COLUMN SEOULANIMALHOSPITAL.LINDPRCBGBNNM IS '축산물가공업구분명';
COMMENT ON COLUMN SEOULANIMALHOSPITAL.BPLCNM IS '사업장명';
COMMENT ON COLUMN SEOULANIMALHOSPITAL.CLGSTDT IS '휴업시작일자';
COMMENT ON COLUMN SEOULANIMALHOSPITAL.RDNPOSTNO IS '도로명우편번호';
COMMENT ON COLUMN SEOULANIMALHOSPITAL.ROPNYMD IS '재개업일자';
COMMENT ON COLUMN SEOULANIMALHOSPITAL.MGTNO IS '관리번호';
COMMENT ON COLUMN SEOULANIMALHOSPITAL.LINDJOBGBNNM IS '축산업무구분명';
COMMENT ON COLUMN SEOULANIMALHOSPITAL.TRDSTATENM IS '영업상태명';
COMMENT ON COLUMN SEOULANIMALHOSPITAL.SITEAREA IS '소재지면적';
COMMENT ON COLUMN SEOULANIMALHOSPITAL.SITETEL IS '전화번호';
COMMENT ON COLUMN SEOULANIMALHOSPITAL.APVCANCELYMD IS '인허가취소일자';
COMMENT ON COLUMN SEOULANIMALHOSPITAL.DTLSTATENM IS '상세영업상태명';
	
TRUNCATE TABLE SEOULANIMALHOSPITAL;

SELECT sitewhladdr FROM SEOULANIMALHOSPITAL;

-- api 다시 해보기
SELECT GUOFFICE FROM SEOUL_ANIMALHOSPITAL;
CREATE TABLE SEOUL_ANIMALHOSPITAL(
LASTMODTS DATE,
DTLSTATENM VARCHAR2(100),
LINDJOBGBNNM VARCHAR2(100),
BPLCNM VARCHAR2(300),
CLGENDDT DATE,
SITEAREA NUMBER,
DCBYMD DATE,
CLGSTDT DATE,
TRDSTATEGBN VARCHAR2(100),
TRDSTATENM VARCHAR2(100),
OPNSFTEAMCODE VARCHAR2(300),
SITETEL VARCHAR2(300),
SITEWHLADDR VARCHAR2(300),
GUOFFICE VARCHAR2(100),
DTLSTATEGBN VARCHAR2(100),
RDNPOSTNO VARCHAR2(100),
UPDATEGBN CHAR(1),
UPDATEDT DATE,
APVPERMYMD DATE,
RDNWHLADDR VARCHAR2(300),
ROPNYMD DATE,
MGTNO VARCHAR2(100)
);

COMMENT ON TABLE SEOUL_ANIMALHOSPITAL IS '서울시_동물병원';

COMMENT ON COLUMN SEOUL_ANIMALHOSPITAL.LASTMODTS IS '최종수정일자';
COMMENT ON COLUMN SEOUL_ANIMALHOSPITAL.DTLSTATENM IS '상세영업상태명';
COMMENT ON COLUMN SEOUL_ANIMALHOSPITAL.LINDJOBGBNNM IS '축산업무구분명';
COMMENT ON COLUMN SEOUL_ANIMALHOSPITAL.BPLCNM IS '사업장명';
COMMENT ON COLUMN SEOUL_ANIMALHOSPITAL.CLGENDDT IS '휴업종료일자';
COMMENT ON COLUMN SEOUL_ANIMALHOSPITAL.SITEAREA IS '소재지면적';
COMMENT ON COLUMN SEOUL_ANIMALHOSPITAL.DCBYMD IS '폐업일자';
COMMENT ON COLUMN SEOUL_ANIMALHOSPITAL.CLGSTDT IS '휴업시작일';
COMMENT ON COLUMN SEOUL_ANIMALHOSPITAL.TRDSTATEGBN IS '영업상태코드';
COMMENT ON COLUMN SEOUL_ANIMALHOSPITAL.TRDSTATENM IS '영업상태명';
COMMENT ON COLUMN SEOUL_ANIMALHOSPITAL.OPNSFTEAMCODE IS '개방자치단체코드';
COMMENT ON COLUMN SEOUL_ANIMALHOSPITAL.SITETEL IS '전화번호';
COMMENT ON COLUMN SEOUL_ANIMALHOSPITAL.SITEWHLADDR IS '지번주소';
COMMENT ON COLUMN SEOUL_ANIMALHOSPITAL.GUOFFICE IS '자치구';
COMMENT ON COLUMN SEOUL_ANIMALHOSPITAL.DTLSTATEGBN IS '상세영업상태코드';
COMMENT ON COLUMN SEOUL_ANIMALHOSPITAL.RDNPOSTNO IS '도로명우편번호';
COMMENT ON COLUMN SEOUL_ANIMALHOSPITAL.UPDATEGBN IS '데이터갱신구분';
COMMENT ON COLUMN SEOUL_ANIMALHOSPITAL.UPDATEDT IS '데이터갱신일자';
COMMENT ON COLUMN SEOUL_ANIMALHOSPITAL.APVPERMYMD IS '인허가일자';
COMMENT ON COLUMN SEOUL_ANIMALHOSPITAL.RDNWHLADDR IS '도로명주소';
COMMENT ON COLUMN SEOUL_ANIMALHOSPITAL.ROPNYMD IS '재개업일자';
COMMENT ON COLUMN SEOUL_ANIMALHOSPITAL.MGTNO IS '관리번호';

TRUNCATE TABLE SEOUL_ANIMALHOSPITAL;



INSERT INTO SEOUL_ANIMALHOSPITAL
(LASTMODTS, DTLSTATENM, LINDJOBGBNNM, BPLCNM, CLGENDDT, DCBYMD, CLGSTDT, TRDSTATEGBN, TRDSTATENM, OPNSFTEAMCODE, SITETEL, SITEWHLADDR, GUOFFICE, DTLSTATEGBN, RDNPOSTNO, UPDATEGBN, UPDATEDT, APVPERMYMD, RDNWHLADDR, ROPNYMD, MGTNO)
VALUES('20220222173635', '폐업', '0', '골드퍼피동물병원 중계점', '0', '20220222', '0', '03', '폐업', '3100000', '02-972-6543', '서울특별시 노원구 공릉동 596-5', '노원구 ', '0002', '01848', 'U', '1638363840000', '20180329', '서울특별시 노원구 동일로 1014, 2층 (공릉동)','0', '310000001020180001');



